import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Docusaurus generates the sidebar from the docs folder structure and each page's
  // sidebar_position front matter.
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
