// <auto-generated />
using System;
using DotMarc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DotMarc.Migrations
{
    [DbContext(typeof(DotMarcDbContext))]
    [Migration("20260903172206_AddDataProtectionKeys")]
    partial class AddDataProtectionKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DomainGroup", b =>
                {
                    b.Property<int>("DomainsId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupsId")
                        .HasColumnType("integer");

                    b.HasKey("DomainsId", "GroupsId");

                    b.HasIndex("GroupsId");

                    b.ToTable("DomainGroup");
                });

            modelBuilder.Entity("DomainTag", b =>
                {
                    b.Property<int>("DomainsId")
                        .HasColumnType("integer");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("DomainsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("DomainTag");
                });

            modelBuilder.Entity("DotMarc.Data.Domain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DmarcCheckDetail")
                        .HasColumnType("text");

                    b.Property<string>("DmarcCheckStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DmarcCheckedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FirstSeenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HaloClientId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMonitored")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastReportReceivedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MtaStsCheckDetail")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("MtaStsCheckedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MtaStsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("MtaStsMaxAgeSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("MtaStsMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("MtaStsMxHosts")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("MtaStsStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TlsrptCheckDetail")
                        .HasColumnType("text");

                    b.Property<string>("TlsrptCheckStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("TlsrptCheckedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Domains");
                });

            modelBuilder.Entity("DotMarc.Data.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("HaloClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("DotMarc.Data.IpInfo", b =>
                {
                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LookedUpUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Organization")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Ip");

                    b.ToTable("IpInfos");
                });

            modelBuilder.Entity("DotMarc.Data.IpRange", b =>
                {
                    b.Property<string>("RangeStart")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("RangeEnd")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LookedUpUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Organization")
                        .HasColumnType("text");

                    b.HasKey("RangeStart", "RangeEnd");

                    b.ToTable("IpRanges");
                });

            modelBuilder.Entity("DotMarc.Data.ParseFailure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("GraphMessageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastAttemptedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GraphMessageId")
                        .IsUnique();

                    b.ToTable("ParseFailures");
                });

            modelBuilder.Entity("DotMarc.Data.PollCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("MessagesChecked")
                        .HasColumnType("integer");

                    b.Property<int>("ParseFailures")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("PolledUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReportsParsed")
                        .HasColumnType("integer");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PolledUtc");

                    b.ToTable("PollCycles");
                });

            modelBuilder.Entity("DotMarc.Data.PollCycleDailySummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("FailedCycles")
                        .HasColumnType("integer");

                    b.Property<int>("SuccessfulCycles")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCycles")
                        .HasColumnType("integer");

                    b.Property<int>("TotalMessagesChecked")
                        .HasColumnType("integer");

                    b.Property<int>("TotalParseFailures")
                        .HasColumnType("integer");

                    b.Property<int>("TotalReportsParsed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("PollCycleDailySummaries");
                });

            modelBuilder.Entity("DotMarc.Data.ProcessedMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GraphMessageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ProcessedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GraphMessageId")
                        .IsUnique();

                    b.ToTable("ProcessedMessages");
                });

            modelBuilder.Entity("DotMarc.Data.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DateRangeBeginUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateRangeEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DomainId")
                        .HasColumnType("integer");

                    b.Property<string>("RawXml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReceivedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReportingOrg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DomainId", "ReportingOrg", "ReportId")
                        .IsUnique();

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("DotMarc.Data.ReportRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DkimResult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeaderFrom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MessageCount")
                        .HasColumnType("integer");

                    b.Property<int>("ReportId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpfResult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportRecords");
                });

            modelBuilder.Entity("DotMarc.Data.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsScopable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("Permissions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DotMarc.Data.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("DotMarc.Data.TlsrptFailureDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInformation")
                        .HasColumnType("text");

                    b.Property<long>("FailedSessionCount")
                        .HasColumnType("bigint");

                    b.Property<string>("FailureReasonCode")
                        .HasColumnType("text");

                    b.Property<string>("ReceivingMxHostname")
                        .HasColumnType("text");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TlsrptReportPolicyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TlsrptReportPolicyId");

                    b.ToTable("TlsrptFailureDetails");
                });

            modelBuilder.Entity("DotMarc.Data.TlsrptReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DateRangeBeginUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateRangeEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DomainId")
                        .HasColumnType("integer");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReceivedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReportingOrg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DomainId", "ReportingOrg", "ReportId")
                        .IsUnique();

                    b.ToTable("TlsrptReports");
                });

            modelBuilder.Entity("DotMarc.Data.TlsrptReportPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("FailedSessionCount")
                        .HasColumnType("bigint");

                    b.Property<string>("PolicyDomain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PolicyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SuccessfulSessionCount")
                        .HasColumnType("bigint");

                    b.Property<int>("TlsrptReportId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TlsrptReportId");

                    b.ToTable("TlsrptReportPolicies");
                });

            modelBuilder.Entity("DotMarc.Data.UserAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntraObjectId")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("UserAccesses");
                });

            modelBuilder.Entity("DotMarc.Notifications.AlertEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalTicketId")
                        .HasColumnType("text");

                    b.Property<string>("ExternalTicketProvider")
                        .HasColumnType("text");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ResolvedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DomainName", "AlertType", "CreatedUtc");

                    b.ToTable("AlertEvents");
                });

            modelBuilder.Entity("DotMarc.Notifications.HaloPsaSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountName")
                        .HasColumnType("text");

                    b.Property<string>("AuthServerUrl")
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<bool>("ClientSecretConfigured")
                        .HasColumnType("boolean");

                    b.Property<int?>("ClosedStatusId")
                        .HasColumnType("integer");

                    b.Property<int?>("DefaultPriorityId")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ProtectedClientSecret")
                        .HasColumnType("text");

                    b.Property<string>("ResourceServerUrl")
                        .HasColumnType("text");

                    b.Property<int?>("TicketTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("WebhookSecret")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HaloPsaSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientSecretConfigured = false,
                            Enabled = false
                        });
                });

            modelBuilder.Entity("DotMarc.Notifications.NotificationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CooldownMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("DeliveryMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("GenericWebhookUrl")
                        .HasColumnType("text");

                    b.Property<int>("MissingReportThresholdDays")
                        .HasColumnType("integer");

                    b.Property<int>("MonitorIntervalSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("TeamsWebhookUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NotificationSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CooldownMinutes = 180,
                            DeliveryMode = "Teams",
                            Enabled = true,
                            MissingReportThresholdDays = 2,
                            MonitorIntervalSeconds = 300
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("UserAccessScopedGroups", b =>
                {
                    b.Property<int>("ScopedGroupsId")
                        .HasColumnType("integer");

                    b.Property<int>("UserAccessId")
                        .HasColumnType("integer");

                    b.HasKey("ScopedGroupsId", "UserAccessId");

                    b.HasIndex("UserAccessId");

                    b.ToTable("UserAccessScopedGroups");
                });

            modelBuilder.Entity("DomainGroup", b =>
                {
                    b.HasOne("DotMarc.Data.Domain", null)
                        .WithMany()
                        .HasForeignKey("DomainsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotMarc.Data.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DomainTag", b =>
                {
                    b.HasOne("DotMarc.Data.Domain", null)
                        .WithMany()
                        .HasForeignKey("DomainsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotMarc.Data.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DotMarc.Data.Report", b =>
                {
                    b.HasOne("DotMarc.Data.Domain", "Domain")
                        .WithMany("Reports")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("DotMarc.Data.ReportRecord", b =>
                {
                    b.HasOne("DotMarc.Data.Report", "Report")
                        .WithMany("Records")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("DotMarc.Data.TlsrptFailureDetail", b =>
                {
                    b.HasOne("DotMarc.Data.TlsrptReportPolicy", "TlsrptReportPolicy")
                        .WithMany("FailureDetails")
                        .HasForeignKey("TlsrptReportPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TlsrptReportPolicy");
                });

            modelBuilder.Entity("DotMarc.Data.TlsrptReport", b =>
                {
                    b.HasOne("DotMarc.Data.Domain", "Domain")
                        .WithMany("TlsrptReports")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("DotMarc.Data.TlsrptReportPolicy", b =>
                {
                    b.HasOne("DotMarc.Data.TlsrptReport", "TlsrptReport")
                        .WithMany("Policies")
                        .HasForeignKey("TlsrptReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TlsrptReport");
                });

            modelBuilder.Entity("DotMarc.Data.UserAccess", b =>
                {
                    b.HasOne("DotMarc.Data.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("UserAccessScopedGroups", b =>
                {
                    b.HasOne("DotMarc.Data.Group", null)
                        .WithMany()
                        .HasForeignKey("ScopedGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotMarc.Data.UserAccess", null)
                        .WithMany()
                        .HasForeignKey("UserAccessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DotMarc.Data.Domain", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("TlsrptReports");
                });

            modelBuilder.Entity("DotMarc.Data.Report", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("DotMarc.Data.TlsrptReport", b =>
                {
                    b.Navigation("Policies");
                });

            modelBuilder.Entity("DotMarc.Data.TlsrptReportPolicy", b =>
                {
                    b.Navigation("FailureDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
