// <auto-generated />
using System;
using System.Collections.Generic;
using DotMarc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DotMarc.Migrations
{
    [DbContext(typeof(DotMarcDbContext))]
    [Migration("20261008235452_AddClientReports")]
    partial class AddClientReports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiKeyScopedGroups", b =>
                {
                    b.Property<int>("ApiKeyId")
                        .HasColumnType("integer");

                    b.Property<int>("ScopedGroupsId")
                        .HasColumnType("integer");

                    b.HasKey("ApiKeyId", "ScopedGroupsId");

                    b.HasIndex("ScopedGroupsId");

                    b.ToTable("ApiKeyScopedGroups");
                });

            modelBuilder.Entity("DomainGroup", b =>
                {
                    b.Property<int>("DomainsId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupsId")
                        .HasColumnType("integer");

                    b.HasKey("DomainsId", "GroupsId");

                    b.HasIndex("GroupsId");

                    b.ToTable("DomainGroup");
                });

            modelBuilder.Entity("DomainTag", b =>
                {
                    b.Property<int>("DomainsId")
                        .HasColumnType("integer");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("DomainsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("DomainTag");
                });

            modelBuilder.Entity("DotMarc.Audit.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ActorEmail")
                        .HasColumnType("text");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActorObjectId")
                        .HasColumnType("text");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("OccurredUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetId")
                        .HasColumnType("text");

                    b.Property<string>("TargetName")
                        .HasColumnType("text");

                    b.Property<string>("TargetType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ActorEmail");

                    b.HasIndex("OccurredUtc")
                        .IsDescending();

                    b.HasIndex("Kind", "OccurredUtc");

                    b.HasIndex("TargetType", "TargetId");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("DotMarc.Audit.AuditSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChangeRetentionDays")
                        .HasColumnType("integer");

                    b.Property<int?>("PageViewRetentionDays")
                        .HasColumnType("integer");

                    b.Property<int?>("SignInRetentionDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AuditSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChangeRetentionDays = 365,
                            PageViewRetentionDays = 90,
                            SignInRetentionDays = 365
                        });
                });

            modelBuilder.Entity("DotMarc.Data.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("LastUsedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("RevokedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("RevokedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("DotMarc.Data.Domain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DkimCheckDetail")
                        .HasColumnType("text");

                    b.Property<string>("DkimCheckStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DkimCheckedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string[]>("DkimSelectors")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("DmarcAuthorizationCheckDetail")
                        .HasColumnType("text");

                    b.Property<string>("DmarcAuthorizationCheckStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DmarcAuthorizationCheckedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DmarcCheckDetail")
                        .HasColumnType("text");

                    b.Property<string>("DmarcCheckStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DmarcCheckedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DmarcPercent")
                        .HasColumnType("integer");

                    b.Property<string>("DmarcPolicy")
                        .HasColumnType("text");

                    b.Property<string>("DmarcSubdomainPolicy")
                        .HasColumnType("text");

                    b.Property<string[]>("DnsNameservers")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("DnsProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DnsProviderCheckedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DnsZone")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FirstSeenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsMonitored")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastReportReceivedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MtaStsCheckDetail")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("MtaStsCheckedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MtaStsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("MtaStsMaxAgeSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("MtaStsMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("MtaStsMxHosts")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("MtaStsStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MxCheckDetail")
                        .HasColumnType("text");

                    b.Property<string>("MxCheckStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("MxCheckedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("SpfCheckDetail")
                        .HasColumnType("text");

                    b.Property<string>("SpfCheckStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SpfCheckedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TlsrptCheckDetail")
                        .HasColumnType("text");

                    b.Property<string>("TlsrptCheckStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("TlsrptCheckedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Domains");
                });

            modelBuilder.Entity("DotMarc.Data.DomainAlertState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Baseline")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("DomainId")
                        .HasColumnType("integer");

                    b.Property<bool>("HasPassed")
                        .HasColumnType("boolean");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset?>("PendingSinceUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RecheckDueUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DomainId", "Item")
                        .IsUnique();

                    b.ToTable("DomainAlertStates");
                });

            modelBuilder.Entity("DotMarc.Data.DomainDkimRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DomainId")
                        .HasColumnType("integer");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Selector")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.HasKey("Id");

                    b.HasIndex("DomainId", "Selector")
                        .IsUnique();

                    b.ToTable("DomainDkimRecords");
                });

            modelBuilder.Entity("DotMarc.Data.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("DotMarc.Data.IpInfo", b =>
                {
                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LookedUpUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Organization")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Ip");

                    b.ToTable("IpInfos");
                });

            modelBuilder.Entity("DotMarc.Data.IpRange", b =>
                {
                    b.Property<string>("RangeStart")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("RangeEnd")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LookedUpUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Organization")
                        .HasColumnType("text");

                    b.HasKey("RangeStart", "RangeEnd");

                    b.ToTable("IpRanges");
                });

            modelBuilder.Entity("DotMarc.Data.ParseFailure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("GraphMessageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastAttemptedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GraphMessageId")
                        .IsUnique();

                    b.ToTable("ParseFailures");
                });

            modelBuilder.Entity("DotMarc.Data.PollCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("MessagesChecked")
                        .HasColumnType("integer");

                    b.Property<int>("ParseFailures")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("PolledUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReportsParsed")
                        .HasColumnType("integer");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PolledUtc");

                    b.ToTable("PollCycles");
                });

            modelBuilder.Entity("DotMarc.Data.PollCycleDailySummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("FailedCycles")
                        .HasColumnType("integer");

                    b.Property<int>("SuccessfulCycles")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCycles")
                        .HasColumnType("integer");

                    b.Property<int>("TotalMessagesChecked")
                        .HasColumnType("integer");

                    b.Property<int>("TotalParseFailures")
                        .HasColumnType("integer");

                    b.Property<int>("TotalReportsParsed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("PollCycleDailySummaries");
                });

            modelBuilder.Entity("DotMarc.Data.ProcessedMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GraphMessageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ProcessedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GraphMessageId")
                        .IsUnique();

                    b.ToTable("ProcessedMessages");
                });

            modelBuilder.Entity("DotMarc.Data.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("AuthDetailBackfilledUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateRangeBeginUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateRangeEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DomainId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ReceivedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReportingOrg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthDetailBackfilledUtc")
                        .HasFilter("\"AuthDetailBackfilledUtc\" IS NULL");

                    b.HasIndex("DomainId", "ReportingOrg", "ReportId")
                        .IsUnique();

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("DotMarc.Data.ReportRawXml", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Xml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RawXml");

                    b.HasKey("Id");

                    b.ToTable("Reports", (string)null);
                });

            modelBuilder.Entity("DotMarc.Data.ReportRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DkimResult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeaderFrom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MessageCount")
                        .HasColumnType("integer");

                    b.Property<int>("ReportId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpfResult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.HasIndex("SourceIp");

                    b.ToTable("ReportRecords");
                });

            modelBuilder.Entity("DotMarc.Data.ReportRecordAuthDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HumanResult")
                        .HasColumnType("text");

                    b.Property<string>("Mechanism")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReportRecordId")
                        .HasColumnType("integer");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Scope")
                        .HasColumnType("text");

                    b.Property<string>("Selector")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReportRecordId");

                    b.ToTable("ReportRecordAuthDetails");
                });

            modelBuilder.Entity("DotMarc.Data.ReportRecordPolicyOverrideReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("ReportRecordId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReportRecordId");

                    b.ToTable("ReportRecordPolicyOverrideReasons");
                });

            modelBuilder.Entity("DotMarc.Data.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsScopable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("Permissions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DotMarc.Data.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("DotMarc.Data.TlsrptFailureDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInformation")
                        .HasColumnType("text");

                    b.Property<long>("FailedSessionCount")
                        .HasColumnType("bigint");

                    b.Property<string>("FailureReasonCode")
                        .HasColumnType("text");

                    b.Property<string>("ReceivingMxHostname")
                        .HasColumnType("text");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TlsrptReportPolicyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TlsrptReportPolicyId");

                    b.ToTable("TlsrptFailureDetails");
                });

            modelBuilder.Entity("DotMarc.Data.TlsrptReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DateRangeBeginUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateRangeEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DomainId")
                        .HasColumnType("integer");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReceivedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReportingOrg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DomainId", "ReportingOrg", "ReportId")
                        .IsUnique();

                    b.ToTable("TlsrptReports");
                });

            modelBuilder.Entity("DotMarc.Data.TlsrptReportPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("FailedSessionCount")
                        .HasColumnType("bigint");

                    b.Property<string>("PolicyDomain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PolicyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SuccessfulSessionCount")
                        .HasColumnType("bigint");

                    b.Property<int>("TlsrptReportId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TlsrptReportId");

                    b.ToTable("TlsrptReportPolicies");
                });

            modelBuilder.Entity("DotMarc.Data.UserAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntraObjectId")
                        .HasColumnType("text");

                    b.Property<bool>("IsClientPortal")
                        .HasColumnType("boolean");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("UserAccesses");
                });

            modelBuilder.Entity("DotMarc.Email.EmailSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FromAddress")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("FromName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("SmtpHost")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<bool>("SmtpPasswordConfigured")
                        .HasColumnType("boolean");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("integer");

                    b.Property<string>("SmtpSecurity")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("SmtpUsername")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.HasKey("Id");

                    b.ToTable("EmailSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Provider = "Off",
                            SmtpPasswordConfigured = false,
                            SmtpPort = 587,
                            SmtpSecurity = "StartTls"
                        });
                });

            modelBuilder.Entity("DotMarc.Notifications.AlertEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ResolvedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DomainName", "AlertType", "CreatedUtc");

                    b.ToTable("AlertEvents");
                });

            modelBuilder.Entity("DotMarc.Notifications.AlertTicketRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("CreateTicket")
                        .HasColumnType("boolean");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlertType")
                        .IsUnique()
                        .HasDatabaseName("IX_AlertTicketRules_AlertType_Global")
                        .HasFilter("\"GroupId\" IS NULL");

                    b.HasIndex("GroupId");

                    b.HasIndex("AlertType", "GroupId")
                        .IsUnique()
                        .HasFilter("\"GroupId\" IS NOT NULL");

                    b.ToTable("AlertTicketRules");
                });

            modelBuilder.Entity("DotMarc.Notifications.AzureDnsSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<bool>("ClientSecretConfigured")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("AzureDnsSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientSecretConfigured = false
                        });
                });

            modelBuilder.Entity("DotMarc.Notifications.CloudflareDnsSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<bool>("ClientSecretConfigured")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("CloudflareDnsSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientSecretConfigured = false
                        });
                });

            modelBuilder.Entity("DotMarc.Notifications.DnsRecordSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SpfAllQualifier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("DnsRecordSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SpfAllQualifier = "SoftFail"
                        });
                });

            modelBuilder.Entity("DotMarc.Notifications.EncryptedSecret", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("ProtectedValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("EncryptedSecrets");
                });

            modelBuilder.Entity("DotMarc.Notifications.GoogleCloudDnsSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<bool>("ClientSecretConfigured")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("GoogleCloudDnsSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientSecretConfigured = false
                        });
                });

            modelBuilder.Entity("DotMarc.Notifications.HaloPsaSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountName")
                        .HasColumnType("text");

                    b.Property<int?>("AssignedAgentId")
                        .HasColumnType("integer");

                    b.Property<string>("AssignedAgentName")
                        .HasColumnType("text");

                    b.Property<string>("AuthServerUrl")
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<bool>("ClientSecretConfigured")
                        .HasColumnType("boolean");

                    b.Property<int?>("ClosedStatusId")
                        .HasColumnType("integer");

                    b.Property<string>("ClosedStatusName")
                        .HasColumnType("text");

                    b.Property<int?>("DefaultPriorityId")
                        .HasColumnType("integer");

                    b.Property<string>("DefaultPriorityName")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ResourceServerUrl")
                        .HasColumnType("text");

                    b.Property<int?>("TicketTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("TicketTypeName")
                        .HasColumnType("text");

                    b.Property<string>("WebhookSecret")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HaloPsaSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientSecretConfigured = false,
                            Enabled = false
                        });
                });

            modelBuilder.Entity("DotMarc.Notifications.NotificationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcknowledgeableAutoCloseDays")
                        .HasColumnType("integer");

                    b.Property<int>("CooldownMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("DkimAlertMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DmarcAlertMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DmarcAuthorizationAlertMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("DmarcPolicyWeakenedEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("GenericWebhookEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("GenericWebhookUrl")
                        .HasColumnType("text");

                    b.Property<int>("MissingReportThresholdDays")
                        .HasColumnType("integer");

                    b.Property<int>("MonitorIntervalSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("MtaStsAlertMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MxAlertMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("NameserversChangedEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("SlackEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("SlackWebhookUrl")
                        .HasColumnType("text");

                    b.Property<string>("SpfAlertMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SuspiciousRejectMinVolume")
                        .HasColumnType("integer");

                    b.Property<int>("SuspiciousRejectNonBenignPercent")
                        .HasColumnType("integer");

                    b.Property<bool>("TeamsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("TeamsWebhookUrl")
                        .HasColumnType("text");

                    b.Property<string>("TlsrptAlertMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("NotificationSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcknowledgeableAutoCloseDays = 0,
                            CooldownMinutes = 180,
                            DkimAlertMode = "WhenItBreaks",
                            DmarcAlertMode = "WhenItBreaks",
                            DmarcAuthorizationAlertMode = "WhenItBreaks",
                            DmarcPolicyWeakenedEnabled = true,
                            Enabled = true,
                            GenericWebhookEnabled = false,
                            MissingReportThresholdDays = 2,
                            MonitorIntervalSeconds = 300,
                            MtaStsAlertMode = "WhenItBreaks",
                            MxAlertMode = "WhenItBreaks",
                            NameserversChangedEnabled = true,
                            SlackEnabled = false,
                            SpfAlertMode = "WhenItBreaks",
                            SuspiciousRejectMinVolume = 10,
                            SuspiciousRejectNonBenignPercent = 50,
                            TeamsEnabled = true,
                            TlsrptAlertMode = "WhenItBreaks"
                        });
                });

            modelBuilder.Entity("DotMarc.Portal.BrandingImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UploadedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("BrandingImages");
                });

            modelBuilder.Entity("DotMarc.Portal.BrandingSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("DarkLogoImageId")
                        .HasColumnType("uuid");

                    b.Property<string>("FooterText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("LogoImageId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrimaryColour")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("SecondaryColour")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("SupportEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("SupportPhone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("SupportUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("BrandingSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PrimaryColour = "#E3594F",
                            ProductName = "dotMARC",
                            SecondaryColour = "#263141"
                        });
                });

            modelBuilder.Entity("DotMarc.Portal.GroupBranding", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DarkLogoImageId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("LogoImageId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrimaryColour")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("SecondaryColour")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.HasKey("GroupId");

                    b.ToTable("GroupBrandings");
                });

            modelBuilder.Entity("DotMarc.Psa.AlertTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlertEventId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastCheckedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Psa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AlertEventId", "Psa")
                        .IsUnique();

                    b.HasIndex("Psa", "TicketId");

                    b.ToTable("AlertTickets");
                });

            modelBuilder.Entity("DotMarc.Psa.Autotask.AutotaskSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClosedStatusId")
                        .HasColumnType("integer");

                    b.Property<string>("ClosedStatusName")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("IntegrationCodeOverride")
                        .HasColumnType("text");

                    b.Property<int?>("IssueTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("IssueTypeName")
                        .HasColumnType("text");

                    b.Property<int?>("PriorityId")
                        .HasColumnType("integer");

                    b.Property<string>("PriorityName")
                        .HasColumnType("text");

                    b.Property<int?>("QueueId")
                        .HasColumnType("integer");

                    b.Property<string>("QueueName")
                        .HasColumnType("text");

                    b.Property<bool>("SecretConfigured")
                        .HasColumnType("boolean");

                    b.Property<int?>("TicketTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("TicketTypeName")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AutotaskSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClosedStatusId = 5,
                            ClosedStatusName = "Complete",
                            Enabled = false,
                            SecretConfigured = false
                        });
                });

            modelBuilder.Entity("DotMarc.Psa.ConnectWise.ConnectWiseSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BoardId")
                        .HasColumnType("integer");

                    b.Property<string>("BoardName")
                        .HasColumnType("text");

                    b.Property<string>("ClientIdOverride")
                        .HasColumnType("text");

                    b.Property<int?>("ClosedStatusId")
                        .HasColumnType("integer");

                    b.Property<string>("ClosedStatusName")
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("PriorityId")
                        .HasColumnType("integer");

                    b.Property<string>("PriorityName")
                        .HasColumnType("text");

                    b.Property<bool>("PrivateKeyConfigured")
                        .HasColumnType("boolean");

                    b.Property<string>("PublicKey")
                        .HasColumnType("text");

                    b.Property<string>("SiteUrl")
                        .HasColumnType("text");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("StatusName")
                        .HasColumnType("text");

                    b.Property<int?>("TypeId")
                        .HasColumnType("integer");

                    b.Property<string>("TypeName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ConnectWiseSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Enabled = false,
                            PrivateKeyConfigured = false
                        });
                });

            modelBuilder.Entity("DotMarc.Psa.PsaCompanyLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("DomainId")
                        .HasColumnType("integer");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Psa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.HasIndex("GroupId");

                    b.HasIndex("Psa", "DomainId")
                        .IsUnique();

                    b.HasIndex("Psa", "GroupId")
                        .IsUnique();

                    b.ToTable("PsaCompanyLinks", t =>
                        {
                            t.HasCheckConstraint("CK_PsaCompanyLinks_OneOwner", "(\"GroupId\" IS NULL) <> (\"DomainId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("DotMarc.Reporting.ClientReports.ClientReportDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("FirstAttemptUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset?>("LastAttemptUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.PrimitiveCollection<List<string>>("Recipients")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTimeOffset?>("SentUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "PeriodStart", "PeriodEnd")
                        .IsUnique()
                        .HasFilter("\"Kind\" = 'Scheduled'");

                    b.ToTable("ClientReportDeliveries");
                });

            modelBuilder.Entity("DotMarc.Reporting.ClientReports.GroupReportSchedule", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.PrimitiveCollection<List<string>>("Recipients")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("StartedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GroupId");

                    b.ToTable("GroupReportSchedules");
                });

            modelBuilder.Entity("DotMarc.Reporting.ClientReports.ReportSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SendHour")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("ReportSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SendHour = 6,
                            TimeZoneId = "UTC"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("UserAccessScopedGroups", b =>
                {
                    b.Property<int>("ScopedGroupsId")
                        .HasColumnType("integer");

                    b.Property<int>("UserAccessId")
                        .HasColumnType("integer");

                    b.HasKey("ScopedGroupsId", "UserAccessId");

                    b.HasIndex("UserAccessId");

                    b.ToTable("UserAccessScopedGroups");
                });

            modelBuilder.Entity("ApiKeyScopedGroups", b =>
                {
                    b.HasOne("DotMarc.Data.ApiKey", null)
                        .WithMany()
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotMarc.Data.Group", null)
                        .WithMany()
                        .HasForeignKey("ScopedGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DomainGroup", b =>
                {
                    b.HasOne("DotMarc.Data.Domain", null)
                        .WithMany()
                        .HasForeignKey("DomainsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotMarc.Data.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DomainTag", b =>
                {
                    b.HasOne("DotMarc.Data.Domain", null)
                        .WithMany()
                        .HasForeignKey("DomainsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotMarc.Data.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DotMarc.Data.ApiKey", b =>
                {
                    b.HasOne("DotMarc.Data.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DotMarc.Data.DomainAlertState", b =>
                {
                    b.HasOne("DotMarc.Data.Domain", null)
                        .WithMany("AlertStates")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DotMarc.Data.DomainDkimRecord", b =>
                {
                    b.HasOne("DotMarc.Data.Domain", null)
                        .WithMany("DkimRecords")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DotMarc.Data.Report", b =>
                {
                    b.HasOne("DotMarc.Data.Domain", "Domain")
                        .WithMany("Reports")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("DotMarc.Data.ReportRawXml", b =>
                {
                    b.HasOne("DotMarc.Data.Report", null)
                        .WithOne("Raw")
                        .HasForeignKey("DotMarc.Data.ReportRawXml", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DotMarc.Data.ReportRecord", b =>
                {
                    b.HasOne("DotMarc.Data.Report", "Report")
                        .WithMany("Records")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("DotMarc.Data.ReportRecordAuthDetail", b =>
                {
                    b.HasOne("DotMarc.Data.ReportRecord", "ReportRecord")
                        .WithMany("AuthDetails")
                        .HasForeignKey("ReportRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportRecord");
                });

            modelBuilder.Entity("DotMarc.Data.ReportRecordPolicyOverrideReason", b =>
                {
                    b.HasOne("DotMarc.Data.ReportRecord", "ReportRecord")
                        .WithMany("OverrideReasons")
                        .HasForeignKey("ReportRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportRecord");
                });

            modelBuilder.Entity("DotMarc.Data.TlsrptFailureDetail", b =>
                {
                    b.HasOne("DotMarc.Data.TlsrptReportPolicy", "TlsrptReportPolicy")
                        .WithMany("FailureDetails")
                        .HasForeignKey("TlsrptReportPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TlsrptReportPolicy");
                });

            modelBuilder.Entity("DotMarc.Data.TlsrptReport", b =>
                {
                    b.HasOne("DotMarc.Data.Domain", "Domain")
                        .WithMany("TlsrptReports")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("DotMarc.Data.TlsrptReportPolicy", b =>
                {
                    b.HasOne("DotMarc.Data.TlsrptReport", "TlsrptReport")
                        .WithMany("Policies")
                        .HasForeignKey("TlsrptReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TlsrptReport");
                });

            modelBuilder.Entity("DotMarc.Data.UserAccess", b =>
                {
                    b.HasOne("DotMarc.Data.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DotMarc.Notifications.AlertTicketRule", b =>
                {
                    b.HasOne("DotMarc.Data.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DotMarc.Portal.GroupBranding", b =>
                {
                    b.HasOne("DotMarc.Data.Group", null)
                        .WithOne()
                        .HasForeignKey("DotMarc.Portal.GroupBranding", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DotMarc.Psa.AlertTicket", b =>
                {
                    b.HasOne("DotMarc.Notifications.AlertEvent", null)
                        .WithMany("Tickets")
                        .HasForeignKey("AlertEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DotMarc.Psa.PsaCompanyLink", b =>
                {
                    b.HasOne("DotMarc.Data.Domain", null)
                        .WithMany("PsaCompanyLinks")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DotMarc.Data.Group", null)
                        .WithMany("PsaCompanyLinks")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DotMarc.Reporting.ClientReports.ClientReportDelivery", b =>
                {
                    b.HasOne("DotMarc.Data.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DotMarc.Reporting.ClientReports.GroupReportSchedule", b =>
                {
                    b.HasOne("DotMarc.Data.Group", null)
                        .WithOne()
                        .HasForeignKey("DotMarc.Reporting.ClientReports.GroupReportSchedule", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserAccessScopedGroups", b =>
                {
                    b.HasOne("DotMarc.Data.Group", null)
                        .WithMany()
                        .HasForeignKey("ScopedGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotMarc.Data.UserAccess", null)
                        .WithMany()
                        .HasForeignKey("UserAccessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DotMarc.Data.Domain", b =>
                {
                    b.Navigation("AlertStates");

                    b.Navigation("DkimRecords");

                    b.Navigation("PsaCompanyLinks");

                    b.Navigation("Reports");

                    b.Navigation("TlsrptReports");
                });

            modelBuilder.Entity("DotMarc.Data.Group", b =>
                {
                    b.Navigation("PsaCompanyLinks");
                });

            modelBuilder.Entity("DotMarc.Data.Report", b =>
                {
                    b.Navigation("Raw")
                        .IsRequired();

                    b.Navigation("Records");
                });

            modelBuilder.Entity("DotMarc.Data.ReportRecord", b =>
                {
                    b.Navigation("AuthDetails");

                    b.Navigation("OverrideReasons");
                });

            modelBuilder.Entity("DotMarc.Data.TlsrptReport", b =>
                {
                    b.Navigation("Policies");
                });

            modelBuilder.Entity("DotMarc.Data.TlsrptReportPolicy", b =>
                {
                    b.Navigation("FailureDetails");
                });

            modelBuilder.Entity("DotMarc.Notifications.AlertEvent", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
